FROM golang:1.15-alpine3.12
RUN apk update && apk add git

MAINTAINER Gopa Kumar <gopa@nextensio.net>
COPY files /go
WORKDIR /go/src/nextensio/controller
COPY db ./db/
COPY nxtsvr ./nxtsvr/
COPY router ./router/
COPY utils ./utils/

RUN go get -d -v ./... \
    && go install -v ./... \
    && \rm -r -f /go/src/nextensio/* \
    && \rm -r -f /go/pkg/mod \
    && \rm -r -f /go/pkg/sumdb

EXPOSE 8080/tcp
CMD /go/bin/nxtsvr
