from lxml import etree

# In the table variable below, enter the html contents from the website 
# https://cyber.harvard.edu/archived_content/people/edelman/fortune-registrars/fortune-list.html
# We can curl that URL and get the html and just paste the contents within the triple quotes below
# The python script just gets column 3 within the html and makes a go array from it
table = '''
'''

parser = etree.HTMLParser()
tree = etree.fromstring(table, parser)
if tree is not None:
    results = tree.xpath('//tr/td[position()=3]')
else:
    results = None

emaildomains = [
    "gmail.com",
	"yahoo.com",
	"microsoft.com",
	"office365.com",
    "godaddy.com",
    ]
print("package db")
print("//NOTE NOTE: This is an autogenerated file, see <workspace root>/files/fortune.py to see how its generated")
print("var Fortune1000 = []string{")
for e in emaildomains:
        print("\"" + e + "\",")
if results is not None:
    for r in results:
        if r.text is not None:
            print("\"" + r.text + "\",")
print("}")
